# Exercise 1: ANOVA {-#ex-1}
## `HSWRESTLER` dataset part I {-#hswrestler} 

To use this data set, you will need to install and use the `PASWR2` package.

To install the `PASWR2` package, use `install.packages("PASWR2)`.

Then enter the following code to obtain the data set `HSWRESTLER`:

<p align = "center">
`library(PASWR2)`
`data(HSWRESTLER)`
</p>

### Constructing an ANOVA table {-#anova-ex}

Construct an ANOVA table using the data in `HSWRESTLER`. Then, test if a linear relationship exists between the hydrostatic fat level (`hwfat`) and tricep fat (`triceps`) using the information in the ANOVA table at the $\alpha = 0.05$ level. 

Start by fitting the model and computing the ANOVA table.

`r hide("Hint: ANOVA table")`
Use the function `anova()` to obtain the ANOVA table.
`r unhide()`

`r hide("Solution: ANOVA table code and output")`
```{r ANOVA-table-ex, eval = TRUE, echo = TRUE}
model.lm <- lm(hwfat ~ triceps, data = HSWRESTLER)
anova(model.lm)
```
`r unhide()`

### Testing for linear relationships {-#test}

Test if a linear relationship exists between `hwfat` and `triceps` using the information in the ANOVA table at the $\alpha = 0.05$ level. 

Step 1: Calculate the rejection region, i.e., $F_{obs}$.

$F_{obs} =$ `r fitb(398.1339)`

`r hide("Hint: How to calculate $F_{obs}$")`
Because $F_{obs} \sim F_{1,76}$ and this is a one-tailed test, the rejection region is $F_{obs} > F_{0.95;1,76} = 3.9691$ (from the statistical tables). The value of the standardised test statistic is $F_{obs} = \frac{MSR}{MSE}$. This is also found in the ANOVA table output (note that the values will be slightly different due to the rounding).
`r unhide()`

`r hide("Solution: $F_{obs}$")`
$F_{obs} = \frac{MSR}{MSE} = \frac{5056.3}{12.7} = 398.1339$
`r unhide()`

Step 2: Use the p-value (`Pr(>|F|))`) in the ANOVA table to determine whether to reject $H_0$ or not.
1. From the rejection region, we `r mcq(c(answer = "reject", "do not reject"))` $H_0$ because $F_{obs}$ is `r mcq(c("less than", answer = "greater than"))` 3.9691.
2. From the p-value, we `r mcq(c(answer = "reject", "do not reject"))` $H_0$ because the value for `Pr(>|F|))` is `r mcq(c("greater than", answer = "less than"))` 0.05.

Step 3: Interpret your results.
There is `r mcq(c(answer = "strong evidence", "insufficient evidence"))` that suggests a linear relationship exists between the variables `hwfat` and `triceps`.

Compute $R^2$ based on `anova(model.lm)` (it should be the same as the value returned in `summary(model.lm)`)

$R^2 =$ `r fitb(0.8402)`

`r hide("Hint: How to calculate $R^2$")`
The formula for $R^2$ is 
$R^2 = \frac{SST}{SST + SSE}$
`r unhide()`

`r hide("Solution: $R^2$")`
$R^2 = \frac{SST}{SST + SSE} = \frac{5056.3}{5056.3+961.5} = 0.8402$
`r unhide()`
