--- 
title: "Practical 3"
author: "Team in 420"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/practical_3
description: "Lab 3 Tutorial"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webexercises")) {
  stop("You must have the 'webexercises' package installed to knit to HTML.\n   install.packages(\"webexercises\")")
} else {
  library("webexercises")
}
library(PASWR2)
data(GRADES)
data(HSWRESTLER)
library(webexercises)
library(tinytex)
library(ggplot2)
library(dplyr)
library(knitr)
diamonds <- read.csv("diamonds.csv")
```

```{r eval=FALSE, echo=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

```{r include=FALSE, echo=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Intended Learning Outcomes {-#ito}

- Obtain the elements of an analysis of variance (ANOVA) table;
- Use the ANOVA table to compute and interpret the F -statistic and its hypothesis test;
- Assess the goodness of fit of linear models based on $R^2$ and $R_a^2$;
- Produce residual plots;
- Assess the assumptions of a linear model using residual plots.
